### PR TITLE
encoding compatible and default output filename

### PR DESCRIPTION
**Pull request by crazyj7**
1. Convert failed in Windows OS of certain languages. 
image

I updated the file open method to automatically check the encoding type.

2. default output file name (same as input file name)
  no need to specify output file name

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
That sounds like a bad idea. Try using Python >=3.7, setting `set PYTHONUTF8=1` and use `ipynb-py-convert` for UTF-8 files only.

Please check it and tell me if it works.

**Comment by kiwi0fruit** [comment]
But I guess always opening as UTF-8 is a good idea until Python 3.8 (or 3.9) released (there is would be default).

This way all other encodings except UTF-8 are deprecated.

I also guess auto naming should by default give error when auromamed output file already exist. But with `-f`/`--force` flag it would be always successful and overwrite.

**Comment by crazyj7** [comment]
> That sounds like a bad idea. Try using Python >=3.7, setting `set PYTHONUTF8=1` and use `ipynb-py-convert` for UTF-8 files only.
> 
> Please check it and tell me if it works.

After the env setting, it worked well. (set PYTHONUTF8=1)

Thanks.

**Comment by kiwi0fruit** [comment]
moved env vars fix to readme. closing.

**Pull request closed without merging**
