### PR TITLE
Support for magics + Automatic output detection (w/ warning)

### PR DESCRIPTION
**Pull request by BardiaKh**
1. Comments out the lines that start with ! or % when converting to py.
2. Automatic output file name based on input. If the file exists, it will ask for confirmation. Users can also pass the `--force` flag to overwrite the output.

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
Looks nice but I need to test if arguments logic works as intended. May be check that ipynb extension is even there on else, or refactor if checks with force like:

```py
force = "--force" in argv
argv = [arg for arg in force if arg != "--force"]
```

**Comment by BardiaKh** [comment]
I see. I will improve this section and let you know.

**Comment by BardiaKh** [comment]
I think it is now what you intended.

**Comment by kiwi0fruit** [comment]
Looks nice. The only inconvenient thing is that we cannot convert back. And actually as we have it now we can define some comments format, that is a sign that we should uncomment the line if it starts from it (when py to ipynb). Like `## %%`, `## !!` or something (so that it doesn't conflict with commonly used comments). Some editors or even jupytext can think that something like ``## %%`` is a cell demarkator. I'll merge this eventually but I first should think up the right format.

**Comment by BardiaKh** [comment]
Yeah totally agree. Maybe using `#!#` and `#%#` as the prefix?

**Comment by BardiaKh** [comment]
If that is reasonable, I can adapt the code.

**Comment by MSFTserver** [comment]
Wow great work, i was just considering doing this didnt notice this discussion but just as a little heads up i made support to get metadata in for notebooks working on both ends and i am using `# !!`

**Comment by MSFTserver** [comment]
Would it be more feasible to instead of stripping them out convert them to subprocess commands?

**Pull request closed without merging**
